name: build

on:
  push:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Disk Cleanup
      run: |
        Get-PSDrive
        # Cache 済み Docker Image の削除
        docker rmi $(docker images -q -a)
        # Android SDK の削除
        Remove-Item -Recurse -Force $Env:ANDROID_HOME
        Remove-Item -Recurse -Force $Env:ANDROID_NDK_HOME
        # JVM の削除
        Remove-Item -Recurse -Force $Env:JAVA_HOME_11_X64
        Remove-Item -Recurse -Force $Env:JAVA_HOME_8_X64
        Remove-Item -Recurse -Force $Env:JAVA_HOME_7_X64
        Get-PSDrive
    - run: .\build.windows.bat
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: webrtc.windows.zip
        path: _package\windows\webrtc.zip
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./build.macos.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: webrtc.macos.tar.gz
        path: _package/macos/webrtc.tar.gz
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        name:
          - raspbian-buster_armv6
          - raspbian-buster_armv7
          - ubuntu-16.04_armv7
          - ubuntu-16.04_x86_64
          - ubuntu-18.04_armv8
          - ubuntu-18.04_x86_64
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Disk Cleanup
      run: docker rmi `docker images -q -a`
    - run: ./build.${{ matrix.name }}.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: webrtc.${{ matrix.name }}.tar.gz
        path: _package/${{ matrix.name }}/webrtc.tar.gz
  create-release:
    name: Create Release
    if: contains(github.ref, 'tags/m')
    needs:
      - build-windows
      - build-macos
      - build-linux
    runs-on: ubuntu-18.04
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Output upload url
      shell: bash
      run: echo "UPLOAD_URL='${{ steps.create_release.outputs.upload_url }}'" > create-release.env
    - name: Upload create-release Environment
      uses: actions/upload-artifact@v1
      with:
        name: create-release.env
        path: create-release.env
  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos
          - raspbian-buster_armv6
          - raspbian-buster_armv7
          - ubuntu-16.04_armv7
          - ubuntu-16.04_x86_64
          - ubuntu-18.04_armv8
          - ubuntu-18.04_x86_64
    name: Release ${{ matrix.name }}
    if: contains(github.ref, 'tags/m')
    needs:
      - create-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Download ${{ matrix.name }}
      uses: actions/download-artifact@v1
      with:
        name: webrtc.${{ matrix.name }}.tar.gz
    - uses: actions/download-artifact@v1
      with:
        name: create-release.env
    - name: Env to output
      shell: bash
      run: |
        source create-release.env/create-release.env
        echo "::set-output name=upload_url::$UPLOAD_URL"
      id: env
    - name: Upload ${{ matrix.name }} Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.env.outputs.upload_url }}
        asset_path: webrtc.${{ matrix.name }}.tar.gz/webrtc.tar.gz
        asset_name: webrtc.${{ matrix.name }}.tar.gz
        asset_content_type: application/gzip
  # Windows だけ Content-Type が違うので別で記述する
  upload-assets-windows:
    name: Upload windows
    if: contains(github.ref, 'tags/m')
    needs:
      - create-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Download windows
      uses: actions/download-artifact@v1
      with:
        name: webrtc.windows.zip
    - uses: actions/download-artifact@v1
      with:
        name: create-release.env
    - name: Env to output
      shell: bash
      run: |
        source create-release.env/create-release.env
        echo "::set-output name=upload_url::$UPLOAD_URL"
      id: env
    - name: Upload windows Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.env.outputs.upload_url }}
        asset_path: webrtc.windows.zip/webrtc.zip
        asset_name: webrtc.windows.zip
        asset_content_type: application/zip
